version: '2'
services:
    uniconnect-app:
        image: uniconnect
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://uniconnect-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=UniConnect
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    uniconnect-mongodb:
        extends:
            file: mongodb.yml
            service: uniconnect-mongodb
